package com.esper.app.core

import android.content.Context
import java.io.PrintWriter
import java.io.StringWriter
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale
import java.util.TimeZone

/**
 * Persists the stack trace from the last uncaught exception so the next launch
 * can hand it to Claude.
 *
 * This is the whole point of the feature: the app crashes, you reopen it, tap
 * "Ask Claude", and the trace is already attached.
 */
object CrashLog {
    private const val PREFS = "esper_crash"
    private const val KEY_TRACE = "last_trace"
    private const val MAX_CHARS = 8_000

    /** Chains to the previous handler so we never swallow a crash. */
    fun install(context: Context) {
        val appContext = context.applicationContext
        val previous = Thread.getDefaultUncaughtExceptionHandler()
        Thread.setDefaultUncaughtExceptionHandler { thread, throwable ->
            runCatching { write(appContext, thread, throwable) }
            previous?.uncaughtException(thread, throwable)
        }
    }

    private fun write(context: Context, thread: Thread, throwable: Throwable) {
        val stamp = SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss'Z'", Locale.US).apply {
            timeZone = TimeZone.getTimeZone("UTC")
        }.format(Date())

        val trace = StringWriter().also { sw ->
            PrintWriter(sw).use { throwable.printStackTrace(it) }
        }.toString()

        val body = "[$stamp] on thread '${thread.name}'\n$trace".take(MAX_CHARS)

        context.getSharedPreferences(PREFS, Context.MODE_PRIVATE)
            .edit()
            .putString(KEY_TRACE, body)
            .commit() // commit, not apply: the process is about to die.
    }

    fun read(context: Context): String? =
        context.getSharedPreferences(PREFS, Context.MODE_PRIVATE)
            .getString(KEY_TRACE, null)
            ?.takeIf { it.isNotBlank() }

    /**
     * Clears the stored trace once the user has acted on it. The trace lives
     * only on the device and is regenerated by the next crash, so this is not
     * destroying anything the user might need later.
     */
    fun clear(context: Context) {
        context.getSharedPreferences(PREFS, Context.MODE_PRIVATE)
            .edit()
            .remove(KEY_TRACE)
            .apply()
    }
}

/**
 * A tiny in-memory ring of breadcrumbs (navigation, network results) that gets
 * attached to a Claude request. Not persisted — it describes this session only.
 */
object EventLog {
    private const val CAPACITY = 30
    private val events = ArrayDeque<String>()

    fun record(message: String) {
        val stamp = SimpleDateFormat("HH:mm:ss", Locale.US).format(Date())
        synchronized(events) {
            if (events.size >= CAPACITY) events.removeFirst()
            events.addLast("$stamp $message")
        }
    }

    fun snapshot(): List<String> = synchronized(events) { events.toList() }
}
